[tool.poetry]
name = "<car_details>"
version = "<0.1>"
description = "<car details>"
authors = [
    {
        "name": "<locky>"
    }
]

[tool.poetry.dependencies]
python_version = "^3.6"



[tool.poetry.dev-dependencies]
